name = "ISA"
uuid = "4900205a-d3d3-4fb7-9198-8c09f5866794"
authors = ["Steven Sandoval"]
version = "0.1.0"

[compat]
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
